### ISSUE TITLE
공지사항

### ISSUE THREAD

**Issue by kyunooh** [9XD/9XD#8]
장고 어드민을 통해서도 충분할 것으로 보이며, 뷰 페이지만 만들 면 될 듯

**Comment by Leop0ld** [comment]
공지사항의 경우에는 따로 Notification(Not Push)을 지원하지는 않나요?

**Comment by kyunooh** [comment]
웹노티를 말씀하시는 거라면 일단 아직은 생각 없습니다... 일을 키우는 건 좋지 않아요 완성후 차근차근

**Comment by kyunooh** [comment]
Complete without design. close issue.
